### ISSUE TITLE
iPhone Calendar URL

### ISSUE THREAD

**Issue by NickSutton** [tybritten/ical-sensor-homeassistant#49] opened 2021-04-12 11:50 UTC
Hi,

I followed this guide to find the URL for the component settings: https://www.techrepublic.com/article/how-to-find-your-icloud-calendar-url/

But was asked for log in information. Is there anywhere this can be entered to link my iCloud calendar with this module?

Thanks,

**Comment by tybritten** [comment] 2022-04-07 13:19
duplicate of https://github.com/tybritten/ical-sensor-homeassistant/issues/78

**Closed by tybritten** 2022-04-07 13:19 UTC
